tap "anomalyco/tap"
tap "oven-sh/bun", trusted: true

# CLI / dev
brew "act"
brew "agent-browser"
brew "cloudflare-wrangler"
brew "cmake"
brew "cocoapods"
brew "ffmpeg"
brew "gh"
brew "git"
brew "go"
brew "gradle"
brew "python@3.14"
brew "jdtls"
brew "ninja"
brew "pipx"
brew "pnpm"
brew "pkgconf"
brew "potrace"
brew "pulumi"
brew "rtk"
brew "starship"
brew "stow"
brew "tmux"
brew "typescript-language-server"
brew "zoxide"
brew "anomalyco/tap/opencode", trusted: true
brew "oven-sh/bun/bun"

# Casks (dev-critical only; other apps stay installed but untracked)
cask "cyberduck"
cask "docker-desktop"
cask "ghostty"
cask "visual-studio-code"
cask "zulu@8"
cask "zulu@17"
cask "zulu@21"

# Editor extensions
vscode "biomejs.biome"
vscode "catppuccin.catppuccin-vsc"
vscode "catppuccin.catppuccin-vsc-icons"
vscode "christian-kohler.npm-intellisense"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "meta.pyrefly"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "pflannery.vscode-versionlens"
vscode "sanjulaganepola.github-local-actions"
vscode "usernamehw.errorlens"
vscode "yoavbls.pretty-ts-errors"
